### ISSUE TITLE
Feature Request; Support isolated files

### ISSUE THREAD

**Issue by Thelm76** [SchabanBo/pub_manager#6]
On my current project we have a mono-repo with nested flutter projects, so we have ~50 different pubspec.yaml, and none in the project's root.

It doesn't seem like your plugin supports this kind of architecture as I get a blank tab when showing package list.

I think the easiest way to support mono-repos would be to add the possibility to launch the tab on any chosen file (like with right-click or currently opened file)

**Comment by SchabanBo** [comment]
Added in V0.3.0. Thanks for suggestions.
